name: Test Latest Commit
on:
  push:
    paths:
      - 'ridant/**'
      - "poetry.lock"
      - "pyproject.toml"
      - "tests/**"
      - ".github/workflows/test_library.yaml"
  workflow_dispatch:

jobs:
  test-library:
    runs-on: ubuntu-latest


    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-port: 6379
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pytest tests