name: Test Latest Commit
on:
  push:
    paths:
      - 'ridant/**'
      - "poetry.lock"
      - "pyproject.toml"
      - "tests/**"
  workflow_dispatch:

jobs:
  test-library:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pytest tests
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis
          # The default Redis port
          REDIS_PORT: 6379